controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\TblRole;
use app\models\TblUser;
use app\components\AccessRule;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => ['logout', 'admin'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['admin'],
                        'allow' => true,
                        'roles' => [
                            TblRole::ROLE_ADMIN
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionAdmin()
    {
        return $this->render('admin');
    }
    
    public function actionRegister()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new \app\models\TblUser(['scenario' => 'register']);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->getSession()->setFlash('success', 'Новый пользователь добавлен. Для завершения регистрации следует подтвердить E-mail, пройдя по ссылке из письма. Письмо отправлено на ' . $model->email);
            return $this->goHome();
        } else {
            return $this->render('register', ['model' => $model]);
        }
    }
    
    public function actionVerifymail($uid, $code)
    {
        $model = \app\models\TblEmailVerification::find()
                ->where(['userId' => $uid, 'code' => $code])
                ->one();
        $user = \app\models\TblUser::findOne($uid);
        if ($model) {
            $user->email_verified = 1;
            $user->save();
            \Yii::$app->user->login($user, 0);
            \Yii::$app->getSession()->setFlash('success', 'Е-mail успешно подтвержден.');
            $model->delete();
        } elseif (!$user) {
            \Yii::$app->getSession()->setFlash('error', 'Пользователь с заданным идентификатором не найден.');
        } else {
            \Yii::$app->getSession()->setFlash('error', 'Код подтверждения неверен или уже был использован ранее.');
        }
        
        return $this->goHome();
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О приложении';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        См. README.md
    </p>
</div>

views/site/admin.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Админка';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Здесь будет происходить управление пользователями</p>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = 'test_task Yii2 Application';
?>
<div class="site-index">
    <div class="jumbotron">
        <h1>test_task</h1>
        <p class="lead">Небольшое yii2 приложение на основе тестового задания</p>
    </div>
    <div class="jumbotron">
        <h2>Суть задания</h2>
        <p style="white-space: pre-line; text-align: left;">
            tbl_user
            id – идентификатор пользователя
            name – имя пользователя
            phone – телефон пользователя
            email – email пользователя
            role_id – роль
            
            tbl_role
            id – идентификатор роли
            title – имя роли
            
            в таблице tbl_roles две записи 1 Администратор 2 Пользователь
            
            Базу и указанные таблицы можно дополнить, если потребуется
            
            Разработать на Yii2 framework мини-сайт. 
            На нем должна быть форма регистрации пользователя с капчей и подтверждением регистрации по email.
            Перед отправкой формы все поля должны пройти валидацию и форма не должна быть отправлена, если какие то из полей заполнены некорректно.
            Пользователю должны быть выданы ошибки – объясняющие, что он сделал неверно и поля, в которых есть ошибки, должны быть залиты красным цветом.
            По умолчанию зарегистрированному пользователю присваивается роль пользователь. После подтверждения регистрации пользователь может авторизоваться на сайте и получить приветственное сообщение Привет, %USERNAME%!
            
            Сделать админку позволяющую редактировать пользователей.
            в tbl_user завести одного пользователя администратора.
            
            Если пользователю присваивается роль Администратор – он тоже может входить в админку и редактировать пользователей.
            
            При просмотре пользователей в админке должны быть фильтры поиска по всем полям. Фильтр по роли сделать выпадающим списком из таблицы ролей tbl_roles
        </p>
    </div>
    <?php if (Yii::$app->user->isGuest) : ?>
    <div class="jumbotron">
        <p>Что дальше?<p>
    </div>
    <div class="body-content">
        <div class="row">
            <div class="col-lg-4">
                <p><a class="btn btn-default" href="<?= Url::to(['site/register']); ?>">Зарегистрироваться &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <p><a class="btn btn-default" href="<?= Url::to(['site/login']); ?>">Войти &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <p><a class="btn btn-default" href="<?= Url::to(['site/about']); ?>">Посмотреть изначальное задание &raquo;</a></p>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Войти';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Для входа в систему пожалуйста заполните следующие поля:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        Нет аккаунта? <a href="<?= Url::to(['site/register']); ?>">Зарегистрироваться</a>.
    </div>
</div>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TblUser */
/* @var $form ActiveForm */
?>
<div class="site-register">
    <h1>Регистрация нового пользователя</h1>
    <?php $form = ActiveForm::begin([
    'id' => 'register-form',
    'options' => ['class' => 'form-horizontal'],
]); ?>

        <?= $form->field($model, 'name') ?>
        <?= $form->field($model, 'phone') ?>
        <?= $form->field($model, 'email') ?>
        <?= $form->field($model, 'password') ?>
        <?= $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::classname()) ?>
        
        <div class="form-group">
            <?= Html::submitButton('Готово', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- site-register -->